### ISSUE TITLE
No popup on old tablet

### ISSUE THREAD

**Issue by Welsyntoffie** [nielsfaber/alarmo-card#110]
Running an old tablet in portrait mode with the whole screen as the alarm keypad.
Latest version only occupies top quarter of the screen and the pop is so dumb, it does not scale.
Little insignificant keypad that is barely usable.

**Comment by FaNt4zMa** [comment]
I agree, please bring back the options to show a keypad under the arming buttons. It was much more user friendly for wall mounted tablet use. The popup is really annoying and makes entering a keypad really cumbersome

![Image](https://github.com/user-attachments/assets/da6fe42e-1bbb-4cd3-80be-cef7de50df32)

**Comment by nielsfaber** [comment]
This issue is fixed by updating to release v1.6.1.

**Comment by FaNt4zMa** [comment]
Updated to 1.6.1 and it still happens on my end... Reverting back to 1.5.2 in the meantime
